name: pohudenieeaai
description: "Приложение для похудения с AI-помощником."
publish_to: 'none' # Убирает публикацию на pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Иконки в стиле iOS
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ---------------------
# Настройки Flutter
# ---------------------
flutter:
  uses-material-design: true

  # Подключение изображений и других ресурсов
  assets:
    - assets/me.png
    - assets/fon.png
    # Если добавишь ещё изображения, просто добавляй строки ниже:
    # - assets/background.png
    # - assets/logo.png

  # Пример подключения кастомных шрифтов (если захочешь)
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 700
